FROM node:18

# Definir o diretório de trabalho
WORKDIR /app

# Copiar package.json e yarn.lock para o contêiner
COPY ./back/package.json ./back/yarn.lock ./

# Instalar as dependências (node_modules)
RUN yarn install

# Instalar nodemon globalmente
RUN yarn global add nodemon

RUN yarn add sequelize mysql2
# Copiar o restante dos arquivos da aplicação
COPY ./back /app

# Expôr a porta 3000 para o servidor
EXPOSE 3000

# Usar o nodemon para rodar a aplicação
CMD ["nodemon", "index.js"]
